### PR TITLE
tweak kots shortcode, drop in a few pointers

### PR DESCRIPTION
**Pull request by dexhorthy**
@breezybaldwin thanks for putting this shortcode together it is lookin' great! I tweaked it a little so we can customize the copy based on the page we're on, but otherwise I think we're ready to start plugging it in

@markpundsack @austinchambers @aj-jester I've started dropping this on a few pages, would love your feedback before we make it an interim policy to drop these in wherever it makes sense. 

Screen Shot 2020-08-16 at 5 33 12 PM
Screen Shot 2020-08-16 at 5 33 19 PM

### CODE REVIEW

**Comment by markpundsack** [comment]
@dexhorthy Looks pretty good. I was a bit confused why the first example only talked about embedded clusters for Kots, and pointed you to kURL. Would it make sense to point to https://kots.io/kotsadm/installing/system-requirements/ instead, or in addition?

First image also has some horizontal space issues between the logo and the text. Looks better in the second example.

**Comment by dexhorthy** [comment]
@markpundsack good catch on the spacing -- @breezybaldwin do you think there's a way to adjust the shortcode styles so this doesn't happen?

**Comment by breezybaldwin** [comment]
> @markpundsack good catch on the spacing -- @breezybaldwin do you think there's a way to adjust the shortcode styles so this doesn't happen?

For sure, I'll work on this now

**Comment by breezybaldwin** [comment]
Screen Shot 2020-08-17 at 6 59 19 PM

**Pull request merged**
