### PR TITLE
kb guide migration

### PR DESCRIPTION
**Pull request by replicatedbart**

### CODE REVIEW

**Comment by replicatedbart** [comment]
Thank you for the feedback Smitha; I made few changes.

**Comment by replicatedbart** [comment]
`did you want to add the new file to the same PR?` not really but since it is already here..., Thanks!

**Comment by dexhorthy** [comment]
Approved, but agree with smitha's comment re: title

> Re: Title - the topic is less about changing the IP on the host, but rather about making the necessary updates to Replicated files in the event of a private IP change.

**Comment by gerred** [comment]
Closed, this was done by moving to Discourse

**Pull request closed without merging**
